Houdini/two_factor_authentication

.travis.yml
Gemfile
spec/lib/two_factor_authentication/models/two_factor_authenticatable_spec.rb
spec/rails_app/config/environments/test.rb

Adds builds to the travisci matrix for Ruby 2.2 and Rails 4.2.4
Also fixes a couple of deprecation warnings that surface as part of
this change.

Test against Ruby 2.2 and Rails 4.2

---

README.md
app/controllers/devise/two_factor_authentication_controller.rb
lib/two_factor_authentication.rb
lib/two_factor_authentication/hooks/two_factor_authenticatable.rb
lib/two_factor_authentication/models/two_factor_authenticatable.rb
spec/features/two_factor_authenticatable_spec.rb
spec/spec_helper.rb
two_factor_authentication.gemspec

This makes the gem store a signed cookie for a configurable amount of
time that allows the user to bypass 2FA. Our use-case for this is that
we expire user’s Devise sessions after 12 hours, but don’t want to
force them to authenticate using 2FA every day.
Signed cookies are available since Rails 3. This requires the signing
functionality to be properly configured, but is disabled by setting the
config variable to `0`, the default.

Add support for remembering a user's 2FA session in a cookie

---

lib/two_factor_authentication.rb
lib/two_factor_authentication/models/two_factor_authenticatable.rb

It is ok when I check it in development environment, but when I run some tests there are many errors ```uninitialized constant Devise::Models::TwoFactorAuthenticatable::InstanceMethodsOnActivation::ROTP```. I think it is because ```require 'rotp'``` is not in appropriate place.

Move require rotp library to the file where it is used

---

.travis.yml

**Why**:
I noticed that recent builds started failing on Travis for no apparent reason. I then saw that Travis was using a different version of bundler compared to builds from 2 months ago. This version of bundler seems to be incompatible with certain versions of Ruby.
By making sure bundler is up to date, it allows Travis to install the gems on all the versions of Ruby that this repo supports.

Update bundler on Travis before installing gems

---

README.md
lib/two_factor_authentication/hooks/two_factor_authenticatable.rb
spec/features/two_factor_authenticatable_spec.rb
spec/rails_app/config/initializers/devise.rb

**Why**
In some cases, it might be necessary to run some code right after the user signs in, but before the OTP is sent, and also right before a user signs out.
For example, consider this scenario:
- The app requires the user to confirm their phone number before it gets saved. This confirmation is done by sending an OTP to the phone and asking the user to enter it.
- User mistypes the number, then closes the anonymous browser window, or signs out before confirming
- User signs back in, and OTP is sent to the mistyped number. User is now unable to fully sign in since the OTP is being sent to the wrong number
In order to prevent this scenario, we need to be able to reset the `unconfirmed_mobile` to nil before the OTP is sent, and before they sign out so that they can type it in again. …

Allow executing code after sign in and before sign out

---

spec/features/two_factor_authenticatable_spec.rb
spec/lib/two_factor_authentication/models/two_factor_authenticatable_spec.rb

`user` was not defined in the specs.

Fix reset_otp_state specs

---

.travis.yml
README.md

**Why**:
The `encryptor` gem, which is used for the new OTP encryption feature,
requires Ruby 2.0 or later.
Also, Rails 5.0 requires Ruby 2.2.2 or greater, so we need to ignore
1.9.3, 2.0, and 2.1 when running RAILS_VERSION=master on Travis.

Drop support for Ruby 1.9.3 & update .travis.yml

---

app/controllers/devise/two_factor_authentication_controller.rb
app/views/devise/two_factor_authentication/show.html.erb
lib/two_factor_authentication/routes.rb

Added the ability for a user to resend the auth code from the two_factor_auth page.

Add ability to resend code

---

lib/two_factor_authentication/hooks/two_factor_authenticatable.rb
spec/features/two_factor_authenticatable_spec.rb
spec/rails_app/app/models/admin.rb
spec/rails_app/app/services/user_otp_sender.rb
spec/rails_app/config/initializers/devise.rb
spec/rails_app/config/routes.rb
spec/rails_app/db/migrate/20160209032439_devise_create_admins.rb
spec/rails_app/db/schema.rb
spec/support/authenticated_model_helper.rb

**Why**:
When looking up a class with `Object.const_defined?`, `false` will be returned the first time it is called, even when the class exists in the Rails app. I think this might be due to the way Rails loads classes.
**How**:
Use `ActiveSupport::Inflector#constantize`, which returns the class all the time when the class exists, and throws a `NameError` when it doesn't.
The only way I was able to properly test this was to create the `UserOtpSender` class as a real file in the test Rails app, and create a Devise Admin user to test the scenario where `AdminOtpSender` does not exist.
I verified that with the old code, `reset_otp_state` was not being called when it should be, and that the new code makes the tests pass.

Fix class detection in reset_otp_state_for(user)

---

app/controllers/devise/two_factor_authentication_controller.rb
spec/features/two_factor_authenticatable_spec.rb
spec/lib/two_factor_authentication/models/two_factor_authenticatable_spec.rb

Flash `:alert` key is more common usage than `:error` for setting errors in rails applications.
In `devise` gem also used `:alert` key ([proof](https://github.com/plataformatec/devise/search?utf8=%E2%9C%93&q=%3Aalert&type=Code))

replaced flash :error key with :alert

---

.travis.yml
README.md

The latest version of Devise requires ruby >= 2.1.
This change removes 2.0 from the test matrix and adds 2.3.

Remove ruby 2.0 from travis build matrix

---

.codeclimate.yml
.rubocop.yml

**Why**:
To specify which Code Climate engines to run, and which Rubocop rules to follow.

Add .rubocop.yml and .codeclimate.yml

---

.codeclimate.yml

**Why**: `bundler-audit` requires `Gemfile.lock` to be checked in, but it is gitignored on purpose in this repo. Enabling bundler-audit causes the Code Climate check to fail, but then seems to also prevent the rest of the engines from running.

Remove bundler-audit from .codeclimate.yml

---

.travis.yml
app/controllers/devise/two_factor_authentication_controller.rb
lib/two_factor_authentication/controllers/helpers.rb
spec/rails_app/app/controllers/home_controller.rb

**Why**: To be able to support Rails 5 without deprecation warnings,
we need to replace `before_filter` with `before_action`.
`before_action` is not supported in Rails 3.2, so we need to bump the
major version number since this will be a breaking change for people
who can't upgrade Rails.

Drop support for Rails 3.2

---

lib/two_factor_authentication/hooks/two_factor_authenticatable.rb

It seems that in some cases `action_dispatch.cookies` is not
set in the environment during the `after_authentication`
hook.

Fix crash in warden hook

---

app/controllers/devise/two_factor_authentication_controller.rb

Hello i found a little glitch in the `after_two_factor_fail_for`. The `set_flash_message` method call `find_message(:attempt_failed)` as second parameter but the method `set_flash_message` from Devise already does a find_message.
```ruby
def set_flash_message(key, kind, options = {})
message = find_message(kind, options)
if options[:now]
flash.now[key] = message if message.present?
else
flash[key] = message if message.present?
end
end
```
Which result in `devise.two_factor_authentication.user.Attempt failed.`
But we want: `devise.two_factor_authentication.user.attempt_failed`
I'm using 
- Devise: 4.2.0
- two_factor_authentication: master

Fix set_flash_message for :attempt_failed

---

README.md
lib/two_factor_authentication/hooks/two_factor_authenticatable.rb
spec/features/two_factor_authenticatable_spec.rb
spec/rails_app/app/services/user_otp_sender.rb

This feature was added so enable and unconfirmed mobile
phone number to be used for OTP purposes and have that
number removed at the start or end of a new session.
However, a simpler way do this would be to simply store
the unconfirmed mobile in the #user_session.  Indeed
that is what we are now doing in 18F identity project
which uses this gem:
https://github.com/18F/identity-idp/pull/220

Remove #reset_otp_state hook

---

app/controllers/devise/two_factor_authentication_controller.rb
spec/support/controller_helper.rb

Squashes two Devise deprecation warnings:
```
DEPRECATION WARNING: [Devise] bypass option is deprecated and it will be removed in future version of Devise.
Please use bypass_sign_in method instead.
Example:
bypass_sign_in(user)
```
```
DEPRECATION WARNING:           [Devise] including `Devise::TestHelpers` is deprecated and will be removed from Devise.
For controller tests, please include `Devise::Test::ControllerHelpers` instead.
```

Updates deprecated Devise methods

---

README.md
app/controllers/devise/two_factor_authentication_controller.rb
lib/two_factor_authentication.rb
lib/two_factor_authentication/hooks/two_factor_authenticatable.rb

@Houdini One of my colleagues reached out to you recently with a security issue that was reported on our platform. Mainly - the same remember 2fa cookie value is used throughout multiple sign ins. So here's a quick attempt to resolve the issue when needed by using the custom method to set value of the cookie.
I also noticed that the exact cookie value is not being tested anywhere in any way, and I'd like very much to change that, but am not sure how exactly tackle this. Could you give me some pointers perhaps?
Or if you are already working on a patch like you mentioned in an email for my colleague, when you expect this to be merged?

Custom resource id field

---

lib/two_factor_authentication/hooks/two_factor_authenticatable.rb

Hi @Houdini!
I've been struggling with the remember option in my app after recent code changes, and when I started digging deeper in the code I noticed that there was a stupid mistake of a comma at the end, that made the expected value... an array. My sincere apologies for this! 😬

Fixed sign in via remember 2fa cookie

---

app/controllers/devise/two_factor_authentication_controller.rb

Currently them gem produces an exception in Rails 5 using the newest devise gem saying `Devise::VERSION` is not set. However, using `respond_to?` works like a charm. Checking a method exists could also be a more preferable approach to ensure that we are using a newer devise gem.

Check and use if newer bypass_sign_in method exists in devise

---

README.md

I made a document change with the understanding that the resource attribute otp_secret_key only needs a value if the user requires a TOTP value. Is that correct?

Doc change re otp_secret_key for version 1 to 2 upgrade

---

lib/two_factor_authentication/models/two_factor_authenticatable.rb
spec/lib/two_factor_authentication/models/two_factor_authenticatable_spec.rb

Removes a deprecation warning from OpenSSL, and updates a test to use the new encryption algorithm from #111.

Fix test and deprecations

---

README.md
lib/two_factor_authentication.rb
lib/two_factor_authentication/hooks/two_factor_authenticatable.rb
lib/two_factor_authentication/models/two_factor_authenticatable.rb
spec/features/two_factor_authenticatable_spec.rb

Delete the cookie when the user logs out to force 2fA again on login.

Delete cookie on logout

---

lib/two_factor_authentication/hooks/two_factor_authenticatable.rb
lib/two_factor_authentication/models/two_factor_authenticatable.rb

- Delegates logic of whether to call `user.send_new_otp` to the `user#send_new_otp_after_login?` method
- Instead of keeping this logic nested in the Warden hook, call a method on the user object to determine if a new OTP code should be delivered.
We realized the need for this upon upgrading from v1 to v2. Our application needs to make a slightly different decision of when the OTP code is delivered via SMS to the user. This is just a small refactor to enable an application to more easily override this business logic by adding a custom `send_new_otp_after_login?` method to the `User` model.
/cc @Houdini @mattmueller @rossta

Delegate logic of whether to send_new_otp to user#send_new_otp_after_login? method

---

app/controllers/devise/two_factor_authentication_controller.rb

The `remember_otp_session_for_seconds` is usually an integer representing seconds, but the expiration calls `from_now` which is not available on integer.
Convert it to seconds.
Scenarios:
- remember_otp_session_for_seconds = 0 - works (will call `0.seconds.from_now`)
- remember_otp_session_for_seconds = 3600 - works  (will call `3600.seconds.from_now`)
- remember_otp_session_for_seconds = 3600.seconds - works (will call `3600.seconds.seconds.from_now`)
Additionally any valid duration that responds to `seconds` can be provided.

Fix integer to seconds in remember_otp_session_for_seconds

---

.travis.yml
Gemfile
spec/controllers/two_factor_authentication_controller_spec.rb
spec/rails_app/db/migrate/20140403184646_devise_create_users.rb
spec/rails_app/db/migrate/20140407172619_two_factor_authentication_add_to_users.rb
spec/rails_app/db/migrate/20140407215513_add_nickanme_to_users.rb
spec/rails_app/db/migrate/20151224171231_add_encrypted_columns_to_user.rb
spec/rails_app/db/migrate/20151224180310_populate_otp_column.rb
spec/rails_app/db/migrate/20151228230340_remove_otp_secret_key_from_user.rb
spec/rails_app/db/migrate/20160209032439_devise_create_admins.rb
spec/rails_app/db/schema.rb
spec/support/authenticated_model_helper.rb
two_factor_authentication.gemspec

- Adds Rails 5 support to specs
- Upgrades capybara dependency for Rails 5 support
- Updates travis build matrix to only run against supported versions of Rails and Ruby
- Enables `fast_finish` in build matrix
- Removes duplicate pry entry in `Gemfile`
- Makes Rails 5.1 the _"default"_ version of in Gemfile
- Normalizes the migration syntax between Rails 4 and Rails 5
**Let me know if you need help maintaining this gem.**
/cc @Houdini @mattmueller @rossta

Improve Travis build matrix; Better Rails 5 coverage

---

lib/two_factor_authentication.rb
lib/two_factor_authentication/orm/active_record.rb

This PR allows working with mongoid when ActiveRecord is not available or not required.

Load ActiveRecord functionality only if ActiveRecord itself is loaded

---

lib/two_factor_authentication/controllers/helpers.rb

fixes Houdini/two_factor_authentication#147

Replace `render :nothing` with `head`

---

lib/two_factor_authentication/models/two_factor_authenticatable.rb
spec/lib/two_factor_authentication/models/two_factor_authenticatable_spec.rb

Some users enter the TOTP code with a space, which breaks authentication. This strips the space from
the user-entered TOTP code and validates against it.
Addresses #155 .

Strip Spaces from TOTP Code

---

lib/two_factor_authentication/models/two_factor_authenticatable.rb

Newer versions of the ROTP gem use a different method for getting a random base32 string. This feature just checks if the random method is available, if not it uses random_base32.

Use ROTP::Base32.random instead of ROTP::Base32.random_base32 if available

---

lib/generators/active_record/templates/migration.rb

The current approach is not great for bigger user bases. I added change to make it safer but to use `algorithm: concurrently` I had to disable transaction, which shouldn't be problem in our case.

Make current migration safe using index concurrently
